-- create tables
create table demo_products (
    id                             number generated by default on null as identity 
                                   constraint demo_products_id_pk primary key,
    name                           varchar2(20 char),
    description                    varchar2(150 char),
    sku                            varchar2(30 char),
    unit                           number,
    unit_price                     number
)
;

-- load data
 
insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    1,
    'M-AABV-47',
    'Tincidunt. Vestibulum ante ipsumprimis in.',
    'Etiam Cursus Porttitor',
    53,
    7
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    2,
    'M-AABK-36',
    'Sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque t',
    'Massa Pharetra Id',
    44,
    18
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    3,
    'M-AAAR-17',
    'Faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus',
    'Nulla Placerat Iaculis',
    82,
    11
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    4,
    'M-AABV-47',
    'Porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Pro',
    'Elit Vestibulum Eget',
    81,
    41
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    5,
    'M-AADK-88',
    'Cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesq',
    'Ac Ante Ipsum',
    55,
    8
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    6,
    'M-AADP-93',
    'Mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis p',
    'Id Mattis Risus',
    8,
    54
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    7,
    'M-AAAX-23',
    'Lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamu',
    'Diam Suscipit Elementum',
    52,
    36
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    8,
    'M-AABN-39',
    'Pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec.',
    'Lacinialectus Quis Consectetur',
    95,
    73
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    9,
    'M-AABP-41',
    'Aliquam. Vestibulum lacinia arcu in.',
    'Vestibulum Ante Ipsumprimis',
    23,
    99
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    10,
    'M-AACT-71',
    'Viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada',
    'Amet Massa Eu',
    68,
    10
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    11,
    'M-AACT-71',
    'Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor',
    'Id Nulla Ac',
    71,
    21
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    12,
    'M-AADG-84',
    'Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi.',
    'Vestibulum Lacinia Arcu',
    37,
    21
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    13,
    'M-AACH-59',
    'Mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis p',
    'Elementum Nulla Facilisi',
    66,
    73
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    14,
    'M-AADG-84',
    'Sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac ',
    'Mattis Risus Rhoncuscras',
    87,
    69
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    15,
    'M-AACS-70',
    'Viverra lacinialectus, quis consectetur mi venenatis.',
    'Viverra Lacinialectus Quis',
    14,
    63
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    16,
    'M-AABS-44',
    'Amet lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam s',
    'Ut Id Nulla',
    20,
    2
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    17,
    'M-AADG-84',
    'Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin.',
    'Proin Viverra Lacinialectus',
    86,
    42
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    18,
    'M-AACY-76',
    'Orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. ',
    'Tristique Ac Volutpat',
    97,
    79
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    19,
    'M-AABP-41',
    'Lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet ma',
    'Ipsum Primis In',
    60,
    36
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    20,
    'M-AAAH-7',
    'Ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ',
    'Suscipit Elementum Sodales',
    71,
    37
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    21,
    'M-AABN-39',
    'Imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate',
    'Viverra Lacinialectus Quis',
    52,
    28
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    22,
    'M-AABQ-42',
    'Et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec conval',
    'Diam Suscipit Elementum',
    19,
    35
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    23,
    'M-AACH-59',
    'Malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lo',
    'Donec Convallis Sollicitudin',
    63,
    91
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    24,
    'M-AABO-40',
    'Amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vul',
    'Tincidunt Vestibulum Ante',
    25,
    66
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    25,
    'M-AACM-64',
    'Malesuada.',
    'Ante Ipsum Primis',
    50,
    45
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    26,
    'M-AACE-56',
    'Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin ele',
    'Etiam Cursus Porttitor',
    71,
    23
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    27,
    'M-AABF-31',
    'Sit amet massa eu lorem commodo ullamcorper.Interdum.',
    'Ullamcorperinterdum Et Malesua',
    97,
    43
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    28,
    'M-AABF-31',
    'Ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat ',
    'Malesuada Fames Ac',
    46,
    9
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    29,
    'M-AACO-66',
    'Non,molestie sit amet lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate portti',
    'Porttitor Ligula Nam',
    91,
    65
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    30,
    'M-AACQ-68',
    'Placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit',
    'Mattis Risus Rhoncuscras',
    31,
    75
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    31,
    'M-AAAN-13',
    'Semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus',
    'Vitae Ligula Commodo',
    100,
    41
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    32,
    'M-AACC-54',
    'Porttitor tincidunt. Vestibulum ante.',
    'Cursus Porttitor Tincidunt',
    22,
    25
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    33,
    'M-AADM-90',
    'Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin ele',
    'Porttitor Tincidunt Vestibulum',
    15,
    47
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    34,
    'M-AABB-27',
    'Ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ',
    'Proin Vulputate Placerat',
    49,
    80
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    35,
    'M-AAAR-17',
    'Semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus',
    'Ut Id Nulla',
    16,
    46
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    36,
    'M-AADV-99',
    'Imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate',
    'Ipsum Primis In',
    53,
    29
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    37,
    'M-AADM-90',
    'Ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis',
    'Nec Donec Convallis',
    68,
    77
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    38,
    'M-AAAP-15',
    'Arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu l',
    'Suscipit Elementum Sodales',
    71,
    57
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    39,
    'M-AAAP-15',
    'Placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posu',
    'Id Mattis Risus',
    91,
    5
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    40,
    'M-AADH-85',
    'Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem.',
    'Commodo Dictum Lorem',
    81,
    63
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    41,
    'M-AAAG-6',
    'Ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consec',
    'Commodo Ullamcorperinterdum Et',
    14,
    68
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    42,
    'M-AADS-96',
    'Lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper',
    'Quis Consectetur Mi',
    59,
    42
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    43,
    'M-AAB2-34',
    'Ac sapien.',
    'Nec Donec Convallis',
    37,
    76
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    44,
    'M-AABK-36',
    'Commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id.',
    'Nulla Placerat Iaculis',
    51,
    65
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    45,
    'M-AABY-50',
    'Mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.In',
    'Iaculis Aliquam Vestibulum',
    40,
    22
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    46,
    'M-AABT-45',
    'Massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat ',
    'Ligula Commodo Dictum',
    82,
    57
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    47,
    'M-AABO-40',
    'Ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat ',
    'Lorem Sit Amet',
    48,
    15
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    48,
    'M-AACD-55',
    'Rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et mal',
    'Ex Etiam Cursus',
    96,
    12
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    49,
    'M-AAAD-3',
    'Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum.',
    'Luctus Et Ultrices',
    14,
    51
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    50,
    'M-AADJ-87',
    'Ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, im',
    'Amet Lectus Nulla',
    71,
    81
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    51,
    'M-AABB-27',
    'Porttitor tincidunt. Vestibulum ante.',
    'Porttitor Ligula Nam',
    60,
    70
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    52,
    'M-AADM-90',
    'Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum.',
    'Sit Amet Lectus',
    31,
    20
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    53,
    'M-AABF-31',
    'Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices.',
    'Placerat Iaculis Aliquam',
    35,
    99
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    54,
    'M-AACV-73',
    'Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristiq',
    'Ipsum Primis In',
    79,
    23
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    55,
    'M-AAAO-14',
    'Vulputate.',
    'Ac Ante Ipsum',
    87,
    34
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    56,
    'M-AABQ-42',
    'Amet lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam s',
    'Suscipit Tristique Ac',
    65,
    18
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    57,
    'M-AACE-56',
    'Faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus',
    'Proin Viverra Lacinialectus',
    39,
    74
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    58,
    'M-AAAH-7',
    'Lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae;',
    'Commodo Ullamcorperinterdum Et',
    54,
    67
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    59,
    'M-AAAO-14',
    'Vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ul',
    'Vestibulum Eget Rhoncus',
    64,
    87
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    60,
    'M-AABE-30',
    'Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo.',
    'Commodo Ullamcorperinterdum Et',
    96,
    74
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    61,
    'M-AAAB-1',
    'Suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum',
    'Porttitor Ligula Nam',
    98,
    3
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    62,
    'M-AABL-37',
    'Fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit am',
    'Lorem Sit Amet',
    68,
    41
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    63,
    'M-AADK-88',
    'Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pell',
    'Ipsumprimis In Faucibus',
    81,
    32
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    64,
    'M-AACF-57',
    'Malesuada fames ac ante ipsum primis in faucibus. Ut id.',
    'Placerat Iaculis Aliquam',
    79,
    85
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    65,
    'M-AABN-39',
    'Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin ele',
    'Massa Eu Lorem',
    55,
    57
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    66,
    'M-AABQ-42',
    'Lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique.',
    'Sit Amet Massa',
    9,
    83
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    67,
    'M-AABS-44',
    'Imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate',
    'Vestibulum Eget Rhoncus',
    39,
    84
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    68,
    'M-AAD2-86',
    'Lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet ma',
    'Pharetra Id Mattis',
    26,
    5
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    69,
    'M-AABM-38',
    'Suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum.',
    'Vulputate Porttitor Ligula',
    68,
    55
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    70,
    'M-AABS-44',
    'Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin ele',
    'Mi Venenatis Nec',
    93,
    21
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    71,
    'M-AADJ-87',
    'Cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin ele',
    'Placerat Pellentesque Proin',
    11,
    30
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    72,
    'M-AAAD-3',
    'Ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae l',
    'Commodo Ullamcorperinterdum Et',
    41,
    55
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    73,
    'M-AAAH-7',
    'Pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo u',
    'Ullamcorperinterdum Et Malesua',
    32,
    58
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    74,
    'M-AAAD-3',
    'Semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus',
    'Tincidunt Vestibulum Ante',
    12,
    51
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    75,
    'M-AACP-67',
    'Malesuada.',
    'Sit Amet Massa',
    1,
    89
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    76,
    'M-AACD-55',
    'Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla f',
    'Proin Viverra Lacinialectus',
    46,
    78
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    77,
    'M-AACN-65',
    'Sollicitudin elementum. Nulla.',
    'Sit Amet Imperdiet',
    69,
    68
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    78,
    'M-AABW-48',
    'Faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus',
    'Placerat Iaculis Aliquam',
    84,
    80
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    79,
    'M-AADE-82',
    'Porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Pro',
    'Proin Viverra Lacinialectus',
    37,
    96
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    80,
    'M-AABJ-35',
    'Posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicit',
    'Mattis Risus Rhoncuscras',
    10,
    93
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    81,
    'M-AADP-93',
    'Id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor ti',
    'Consectetur Mi Venenatis',
    63,
    31
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    82,
    'M-AADE-82',
    'Id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor ti',
    'Curae; Proin Vulputate',
    29,
    61
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    83,
    'M-AABG-32',
    'Et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec conval',
    'Mattis Risus Rhoncuscras',
    46,
    26
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    84,
    'M-AABY-50',
    'Fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula.',
    'Ante Ipsum Primis',
    7,
    49
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    85,
    'M-AAB2-34',
    'Sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin',
    'Vitae Ligula Commodo',
    22,
    97
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    86,
    'M-AAAJ-9',
    'Porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Pro',
    'Amet Massa Eu',
    27,
    4
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    87,
    'M-AADL-89',
    'Convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae.',
    'Ut Id Nulla',
    71,
    70
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    88,
    'M-AAC1-72',
    'Sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin',
    'Faucibus Ut Id',
    31,
    37
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    89,
    'M-AAAM-12',
    'Faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venena',
    'Lacinia Arcu In',
    22,
    46
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    90,
    'M-AACC-54',
    'Faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus',
    'Rhoncuscras Vulputate Porttito',
    46,
    13
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    91,
    'M-AAB2-34',
    'Venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posu',
    'Venenatis Nec Donec',
    96,
    5
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    92,
    'M-AACX-75',
    'Ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae l',
    'Ex Etiam Cursus',
    61,
    23
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    93,
    'M-AABW-48',
    'Id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor ti',
    'Donec Convallis Sollicitudin',
    79,
    46
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    94,
    'M-AABH-33',
    'Ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis i',
    'Id Mattis Risus',
    34,
    43
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    95,
    'M-AADO-92',
    'Id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper',
    'Amet Massa Eu',
    57,
    20
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    96,
    'M-AABS-44',
    'Nec.',
    'Ac Ante Ipsum',
    72,
    18
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    97,
    'M-AADQ-94',
    'Posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicit',
    'Proin Viverra Lacinialectus',
    38,
    57
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    98,
    'M-AACG-58',
    'Lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamu',
    'Id Mattis Risus',
    28,
    81
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    99,
    'M-AADR-95',
    'Ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis i',
    'Ante Ipsum Primis',
    29,
    63
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    100,
    'M-AAAN-13',
    'Ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ',
    'Porttitor Ligula Nam',
    98,
    30
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    101,
    'M-AACH-59',
    'Risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum ',
    'Nec Donec Convallis',
    35,
    55
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    102,
    'M-AAAN-13',
    'Vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus.',
    'Amet Massa Eu',
    65,
    95
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    103,
    'M-AAAH-7',
    'Porttitor tincidunt. Vestibulum.',
    'Ut Id Nulla',
    48,
    62
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    104,
    'M-AABS-44',
    'Sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque t',
    'Faucibus Ut Id',
    18,
    1
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    105,
    'M-AAAR-17',
    'Eget rhoncus non,molestie sit amet lectus. Nulla.',
    'Nulla Placerat Iaculis',
    42,
    29
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    106,
    'M-AAAD-3',
    'Amet lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam s',
    'Amet Massa Eu',
    64,
    10
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    107,
    'M-AACP-67',
    'Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam su',
    'In Faucibus Orci',
    100,
    68
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    108,
    'M-AADH-85',
    'Faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venena',
    'Placerat Pellentesque Proin',
    98,
    85
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    109,
    'M-AADC-80',
    'Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget mal',
    'Pharetra Id Mattis',
    63,
    85
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    110,
    'M-AAC2-60',
    'Nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi max',
    'Lorem Commodo Ullamcorperinter',
    33,
    36
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    111,
    'M-AACF-57',
    'Amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volu',
    'Nonmolestie Sit Amet',
    10,
    14
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    112,
    'M-AADS-96',
    'Cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesq',
    'Ligula Commodo Dictum',
    89,
    53
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    113,
    'M-AADB-79',
    'Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pell',
    'Id Nulla Ac',
    91,
    100
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    114,
    'M-AABH-33',
    'Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialec',
    'Luctus Et Ultrices',
    66,
    84
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    115,
    'M-AABR-43',
    'Elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ipsum tellus, quis posuere mi maximus vitae. Quisque tortor odio, f',
    'Pharetra Id Mattis',
    73,
    84
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    116,
    'M-AACY-76',
    'Vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilis',
    'Posuere Cubilia Curae;',
    97,
    27
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    117,
    'M-AADK-88',
    'Porttitor tincidunt. Vestibulum.',
    'Ante Ipsum Primis',
    74,
    100
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    118,
    'M-AAAX-23',
    'Sollicitudin.',
    'In Massa Pharetra',
    29,
    73
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    119,
    'M-AAAD-3',
    'Nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tinci',
    'Nam Semper Diam',
    13,
    92
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    120,
    'M-AABM-38',
    'Elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapi',
    'Massa Eu Lorem',
    85,
    51
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    121,
    'M-AACH-59',
    'Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pell',
    'Orci Luctus Et',
    63,
    62
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    122,
    'M-AABP-41',
    'Vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ',
    'Id Mattis Risus',
    32,
    5
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    123,
    'M-AAAY-24',
    'Massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem com',
    'Primis In Faucibus',
    62,
    21
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    124,
    'M-AAAZ-25',
    'Ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat ',
    'Id Mattis Risus',
    16,
    87
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    125,
    'M-AAAL-11',
    'Vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ul',
    'Massa Pharetra Id',
    88,
    7
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    126,
    'M-AABO-40',
    'Amet lectus. Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam s',
    'Ligula Commodo Dictum',
    91,
    6
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    127,
    'M-AABG-32',
    'Risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum ',
    'Amet Lectus Nulla',
    2,
    39
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    128,
    'M-AACR-69',
    'Placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posu',
    'Amet Lectus Nulla',
    9,
    61
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    129,
    'M-AABV-47',
    'Sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin',
    'Volutpat Risusphasellus Vitae',
    89,
    66
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    130,
    'M-AACH-59',
    'Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in fauc',
    'Vulputate Porttitor Ligula',
    42,
    80
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    131,
    'M-AADN-91',
    'Eget rhoncus non,molestie sit amet lectus. Nulla.',
    'Lorem Commodo Ullamcorperinter',
    87,
    61
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    132,
    'M-AACF-57',
    'Ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis',
    'Ex Etiam Cursus',
    23,
    35
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    133,
    'M-AACW-74',
    'Vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis in faucibus orci luctus et ul',
    'Amet Lectus Nulla',
    57,
    9
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    134,
    'M-AABZ-51',
    'Sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac ',
    'Nec Donec Convallis',
    50,
    32
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    135,
    'M-AACX-75',
    'Commodo ullamcorper.Interdum.',
    'Primis In Faucibus',
    3,
    68
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    136,
    'M-AADA-78',
    'Ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, im',
    'Porttitor Ligula Nam',
    32,
    70
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    137,
    'M-AADG-84',
    'Vestibulum ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialec',
    'Curae; Proin Vulputate',
    9,
    25
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    138,
    'M-AACF-57',
    'Rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et mal',
    'Aliquam Vestibulum Lacinia',
    69,
    17
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    139,
    'M-AADA-78',
    'Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam suscipit elementum sodales. Proin ',
    'Commodo Ullamcorperinterdum Et',
    44,
    14
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    140,
    'M-AACB-53',
    'Nulla placerat iaculis aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam su',
    'Vulputate Placerat Pellentesqu',
    35,
    3
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    141,
    'M-AABT-45',
    'Aliquam. Vestibulum lacinia arcu in massa pharetra, id mattis risus rhoncus.Cras vulputate porttitor ligula. Nam semper diam.',
    'Placerat Iaculis Aliquam',
    26,
    8
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    142,
    'M-AABX-49',
    'Malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lo',
    'Vestibulum Ante Ipsumprimis',
    39,
    96
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    143,
    'M-AADN-91',
    'Suscipit elementum sodales. Proin sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id null',
    'Curae; Proin Vulputate',
    2,
    28
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    144,
    'M-AACM-64',
    'Ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis',
    'Proin Viverra Lacinialectus',
    18,
    47
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    145,
    'M-AABT-45',
    'In faucibus. Ut id nulla ac sapien suscipit tristique ac volutpat risus.Phasellus vitae ligula commodo, dictum lorem sit amet, imperdiet ex. Etiam cur',
    'Faucibus Ut Id',
    44,
    45
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    146,
    'M-AADW-100',
    'Sit amet massa eu lorem commodo ullamcorper.Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut id nulla ac sapien suscipit tristique ac ',
    'Proin Viverra Lacinialectus',
    44,
    17
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    147,
    'M-AACF-57',
    'Imperdiet ex. Etiam cursus porttitor tincidunt. Vestibulum ante ipsumprimis.',
    'Tincidunt Vestibulum Ante',
    74,
    61
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    148,
    'M-AADT-97',
    'Quis consectetur mi venenatis nec. Donec convallis sollicitudin elementum. Nulla facilisi. In posuere blandit leoeget malesuada. Vivamus efficitur ips',
    'Nec Donec Convallis',
    81,
    56
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    149,
    'M-AABA-26',
    'Ante ipsumprimis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis c',
    'Eu Lorem Commodo',
    73,
    13
);

insert into demo_products (
    id,
    name,
    description,
    sku,
    unit,
    unit_price
) values (
    150,
    'M-AACZ-77',
    'Posuere cubilia Curae; Proin vulputate placerat pellentesque. Proin viverra lacinialectus, quis consectetur mi venenatis nec. Donec convallis sollicit',
    'Ante Ipsum Primis',
    4,
    45
);

commit;

alter table demo_products
modify id generated by default on null as identity restart start with 151;
 
-- load data
